### ISSUE TITLE
Insufficient tests for isValid function

### ISSUE THREAD

**Issue by johnondrej** [MI-AFP/hw02#3]
Provided tests for `isValid` function currently don't cover case when order is correct in root, but incorrect in some subtree. As a consequence, function that checks only root and its closest children will pass all the tests.

Example of incorrect function passing the tests:
```
isValid :: Ord a => BSTree a -> Bool
isValid Nil = True
isValid (Node x l r) = (l == Nil || value l <= x) && (r == Nil || x <= value r)
```

Example of invalid tree that is rated as valid by function above:
```    
      42
  8       60
9   1
```

**Comment by scheras** [comment]
Solved in #2?

**Comment by johnondrej** [comment]
I didn't notice the PR. You are right, it solves the problem.

**Comment by MarekSuchanek** [comment]
#2 is now merged, `git pull assignment master` should do the work from now on
